apiVersion: v1
kind: Service
metadata:
  name: gc-customerms-svc
  namespace: greencompute
  labels:
    app: greencompute-customerms
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    app: greencompute-customerms
